name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v18.8.0
      - name: Install dependencies
        run: npm ci
      - name: Build site
        env:
          SECRET_GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: npm run build
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: dist
          retention-days: 3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: site
      - name: Deploy site
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr
          path: site/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
