name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v18.8.0
      - name: Install dependencies
        run: npm ci
      - name: Build site
        env:
          SECRET_GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: npm run build
      - name: List files
        run: ls -l
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: dist
          retention-days: 3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: site
      - name: Deploy site
        run: ls -l
